swagger: '2.0'
info:
  description: Possible API endpoints for phase two of Argent Bank project.
  version: 1.0.0
  title: Argent Bank API documentation
  termsOfService: http://swagger.io/terms/
host: virtserver.swaggerhub.com
basePath: /JeremyANGELE/argentBank/1.0.0
schemes:
  - https
  - http
paths:
  /accounts:
    get:
      tags:
        - User Accounts
      summary: Summary of user's accounts
      description: Get user's accounts summary
      produces:
        - application/json
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          required: true
          type: string
      responses:
        '200':
          description: User summary accounts retrieved succesfully
          schema:
            $ref: '#/definitions/Accounts_Response'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      security:
        - Bearer: []
  /accounts/{accountId}/transactions:
    get:
      tags:
        - User Accounts Transactions
      summary: Transactions for the selected account
      description: Get account transactions
      operationId: userTransaction
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: accountId
          in: path
          description: ID of the account to get
          required: true
          type: integer
      responses:
        '200':
          description: User account transactions retrieved succesfully
          schema:
            $ref: '#/definitions/Transactions_Response'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      security:
        - Bearer: []
    post:
      tags:
        - User Accounts Transactions
      summary: add transaction
      description: add transaction in account
      operationId: addTransaction
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: accountId
          in: path
          description: ID of the account to get
          required: true
          type: integer
        - in: body
          name: body
          description: add transaction in account
          required: true
          schema:
            $ref: '#/definitions/TransactionAdd'
      responses:
        '200':
          description: Transaction added succesfully
          schema:
            $ref: '#/definitions/TransactionAdd_Response'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      security:
        - Bearer: []
  /accounts/{accountId}/{month}/transactions/:
    get:
      tags:
        - User Accounts Transactions
      summary: Transactions month for the selected account
      description: Get account transactions for a month
      operationId: userTransactionMonth
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: accountId
          in: path
          description: ID of the account to get
          required: true
          type: integer
        - name: month
          in: path
          description: number month
          required: true
          type: integer
      responses:
        '200':
          description: User account transactions month retrieved succesfully
          schema:
            $ref: '#/definitions/TransactionsMonth_Response'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      security:
        - Bearer: []
  /accounts/{accountId}/transactions/{transactionId}:
    get:
      tags:
        - User Account Transactions Details
      summary: Transaction details for the selected transaction ID
      description: Get details for the selected transaction
      operationId: userTransactionDetail
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: accountId
          in: path
          description: ID of the account to get
          required: true
          type: integer
        - name: transactionId
          in: path
          description: ID of the transaction to get
          required: true
          type: integer
      responses:
        '200':
          description: User transaction details retrieved succesfully
          schema:
            $ref: '#/definitions/Transaction_Details_Response'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      security:
        - Bearer: []
    put:
      tags:
        - User Account Transactions Details
      summary: Update transaction details
      description: Update details for the selected transaction
      operationId: userTransactionDetailUpdate
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: accountId
          in: path
          description: ID of the account to get
          required: true
          type: integer
        - name: transactionId
          in: path
          description: ID of the transaction to get
          required: true
          type: integer
        - in: body
          name: body
          description: Update transaction details
          required: true
          schema:
            $ref: '#/definitions/Transaction_Details'
      responses:
        '200':
          description: Transaction details updated succesfully
          schema:
            $ref: '#/definitions/Transaction_Details_Response'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      security:
        - Bearer: []
    delete:
      tags:
        - User Account Transactions Details
      summary: Delete transaction
      description: Delete transaction for the selected transaction
      operationId: userTransactionDetaildelete
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: accountId
          in: path
          description: ID of the account to get
          required: true
          type: integer
        - name: transactionId
          in: path
          description: ID of the transaction to get
          required: true
          type: integer
      responses:
        '200':
          description: Transaction delete succesfully
          schema:
            $ref: '#/definitions/Transaction_Delete_Response'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      security:
        - Bearer: []
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Accounts_Response:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
        example: User accounts retrieved succesfully
      body:
        type: array
        items:
          $ref: '#/definitions/Account'
  TransactionsMonth_Response:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
        example: User transactions month retrieved succesfully
      body:
        type: array
        items:
          $ref: '#/definitions/Transaction'
  Transactions_Response:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
        example: User transactions retrieved succesfully
      body:
        type: array
        items:
          $ref: '#/definitions/Transaction'
  TransactionAdd_Response:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
        example: User transaction added retrieved succesfully
      body:
        type: array
        items:
          type: object
          properties:
            id:
              type: integer
              example: 24
              description: Transaction ID
            created:
              type: string
              example: '2020-06-21'
              description: Transaction date
            description:
              type: string
              example: Golden sun bakery
              description: Transaction description
            amount:
              type: number
              example: 6
              description: Transaction amount
            balance:
              type: number
              example: 2082.79
              description: Account balance after transaction
            currency:
              type: string
              example: €
  Transaction_Details_Response:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
        example: User transaction details retrieved succesfully
      body:
        type: array
        items:
          $ref: '#/definitions/Transaction_Details'
  Transaction_Delete_Response:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
        example: User transaction delete succesfully
  Account:
    type: object
    properties:
      id:
        type: integer
        example: 1
        description: account ID
      created:
        type: string
        description: Account Creation Date
      name:
        type: string
        example: Argent Bank Checking
      type:
        type: string
        example: x8349
      balance:
        type: number
        example: 2082.79
      currency:
        type: string
        example: €
  Transaction:
    type: object
    properties:
      id:
        type: integer
        example: 23
        description: Transaction ID
      created:
        type: string
        example: '2020-06-20'
        description: Transaction date
      description:
        type: string
        example: Golden sun bakery
        description: Transaction description
      amount:
        type: number
        example: 5
        description: Transaction amount
      balance:
        type: number
        example: 2082.79
        description: Account balance after transaction
      currency:
        type: string
        example: €
  TransactionAdd:
    type: object
    properties:
      description:
        type: string
        example: Golden sun bakery
        description: Transaction description
      transactionType:
        type: string
        example: Electronic
        description: Transaction type
      category:
        type: string
        example: Food
        description: Transaction category
      note:
        type: string
        description: User's notes for the transaction
      amount:
        type: number
        example: 6
        description: Transaction amount
  Transaction_Details:
    type: object
    properties:
      id:
        type: integer
        description: Transaction ID
      transactionType:
        type: string
        description: Transaction type
      category:
        type: string
        description: Transaction category
      note:
        type: string
        description: User's notes for the transaction
